### ISSUE TITLE
1) Bug fix: Sending messages

### ISSUE THREAD

**Issue by SV62** [akinolu52/turbo-rotary#7]
There are some bugs in our starting code that we would like you to investigate and resolve. First, when you send a new message, it does not immediately appear on the screen. We would like new messages to be immediately added to the chat UI for both existing conversations and new conversations. (Note: This may require more than one change)
Additionally, messages are not displayed in the correct order on page load. Messages should be displayed in order with the oldest messages at the top and newest messages at the bottom.

Note: All fixes for these bugs can be done on the front end

**Comment by akinolu52** [comment]
@SV62 i cant replicate the first issue where message doesnt not show on the screen immediately, any pointer(s) on how to replicate it or can you send a short video which highlight this issue?

**Comment by akinolu52** [comment]
A [PR](https://github.com/akinolu52/turbo-rotary/pull/10) to fix sending messages issues
