### ISSUE TITLE
2) Feature: New design for login/signup pages

### ISSUE THREAD

**Issue by SV62** [akinolu52/turbo-rotary#8]
We’ve received new specs from our designer. Please implement the design for the login and signup pages, and make it mobile responsive. The design spec and needed assets are available in [this zip folder](https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/project-overview/assets.zip). The spec may need a bit of adapting to fit our use case, so please use your best judgement.

Please include a couple of screenshots in the description when making this PR to showcase the styling you've done.

**Comment by akinolu52** [comment]
A [PR](https://github.com/akinolu52/turbo-rotary/pull/11) to fix sending messages issues
