### ISSUE TITLE
3) Feature - Sending images - front end

### ISSUE THREAD

**Issue by SV62** [akinolu52/turbo-rotary#9]
We would like for users to be able to send images. We would like you to implement the front end of this feature, and merge it into a branch named feature-sending-images. [In an actual work environment, another engineer on the team would complete the back end portion of this feature and merge it into the same branch, but this will not be included as part of the project interview.] This feature is described in depth on [this page](https://docs.google.com/document/d/1CYkj5NkprQccpZjJHHrFzPGLeBtTMH9375HyrqzIT3s/edit?usp=sharing).

**Comment by akinolu52** [comment]
A [PR](https://github.com/akinolu52/turbo-rotary/pull/12/) to fix sending images issues

<img width="1440" alt="Screenshot 2021-08-11 at 03 18 58" src="https://user-images.githubusercontent.com/16763860/128959822-e4a567fb-14fe-4323-8e05-5860e116a333.png">
<img width="1440" alt="Screenshot 2021-08-11 at 03 19 05" src="https://user-images.githubusercontent.com/16763860/128959832-a857c8de-e771-4145-a460-6fb3671edc20.png">
<img width="1440" alt="Screenshot 2021-08-11 at 03 19 29" src="https://user-images.githubusercontent.com/16763860/128959835-339d8bcc-9a59-473e-a52f-23e1675bf9d0.png">
